include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules
    prefer_single_quotes: true
    avoid_print: false # Allow print statements in examples
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_locals: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
